feat: add basic typescript declaration file
ungap/global-this pull request #5
Opened 2019-11-27 21:11 UTC by christopherthielen

closes #3

2019-11-27 21:11 UTC, christopherthielen commented on cjs/index.d.ts
> +declare const globaThis: any;
this file won't actually be used, but I put it here to be consistent between the two

2019-11-28 04:08 UTC, ExE-Boss commented on cjs/index.d.ts
> +export default globaThis;
This is incorrect.

2019-11-28 04:21 UTC, ExE-Boss requested changes
The&nbsp;type&nbsp;should be&nbsp;`typeof globalThis`.

And&nbsp;the&nbsp;`cjs/index.d.ts`&nbsp;export should&nbsp;represent&nbsp;the&nbsp;shape of&nbsp;the&nbsp;module/library&nbsp;[correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html).

2019-11-28 04:21 UTC, ExE-Boss commented on cjs/index.d.ts
> +export default globaThis;
[This is incorrect.](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)

2020-03-04 20:28 UTC, closed without merging